#!/usr/bin/env bash
# exports - environment variables configuration

# Set paths to dotfiles and local override directories.
DOTFILES=$HOME/.dotfiles
DOTFILES_LOCAL=$DOTFILES/local

# Set editor to `vim`.
export EDITOR='vim'
export VISUAL="$EDITOR"

# Source local override file if one exists.
[ -r "$DOTFILES_LOCAL"/exports ] && . "$DOTFILES_LOCAL"/exports
