#!/usr/bin/env bash
# prompt - bash prompt

# Set paths to dotfiles and local override directories.
DOTFILES=$HOME/.dotfiles
DOTFILES_LOCAL=$DOTFILES/local

# Gentoo/cygwin style prompt.
export PS1='\[\e[0;32m\]\u\[\e[0;36m\]@\[\e[0;32m\]\h\[\e[1;34m\] \w\[\e[0;32m\]\n\[\e[00m\]\$ '

# Source local override file if one exists.
[ -r "$DOTFILES_LOCAL"/prompt ] && . "$DOTFILES_LOCAL"/prompt
