# vim:ft=kitty
## name: Kanagawa
## author: Eric N. Vander Weele
## license: MIT
## upstream: https://github.com/rebelot/kanagawa.nvim
## blurb: Kanagawa Wave Theme modified to follow the Kitty Themes
##        template.conf.

#: Basic colors
foreground           #dcd7ba
background           #1f1f28
selection_foreground #d8dee9
selection_background #434c5e

#: Cursor colors
cursor            #dcd7ba
cursor_text_color #2a2a37

#: URL underline color when hovering with mouse
url_color #0087bd

#: Window border colors and terminal bell colors
active_border_color   #81a1c1
inactive_border_color #4c566a
bell_border_color     #88c0d0
visual_bell_color     none

#: Tab bar colors
active_tab_foreground   #3b4252
active_tab_background   #88c0d0
inactive_tab_foreground #e5e9f0
inactive_tab_background #4c566a
tab_bar_background      #3b4252
tab_bar_margin_color    none

#: Mark colors (marked text in the terminal)
mark1_foreground #3b4252
mark1_background #88c0d0
mark2_foreground #3b4252
mark2_background #bf616a
mark3_foreground #3b4252
mark3_background #ebcb8b

#: The basic 16 colors
#: black
color0 #16161d
color8 #727169

#: red
color1 #c34043
color9 #e82424

#: green
color2  #76946a
color10 #98bb6c

#: yellow
color3  #ca0a36e
color11 #e6c384

#: blue
color4  #7e9cd8
color12 #7fb4ca

#: magenta
color5  #957fb8
color13 #938aa9

#: cyan
color6  #88c0d0
color14 #8fbcbb

#: white
color7  #e5e9f0
color15 #eceff4
