# .kitty.conf — kitty terminal configuration
# vim: foldmethod=marker

#: Fonts {{{

# https://www.monolisa.dev/
# dlig: Programming ligatures.
# cv07: Alt greater-equal with flat underline.
# ss12: Thin double backslash.
# ss13: Hexadecimal x for 0x#.
# ss01: Script variant glyphs for italics.

# BEGIN_KITTY_FONTS
font_family      family=MonoLisaCode variable_name=MonoLisaCodeRegular style=MonoLisaCode-Regular features='dlig cv07 ss12 ss13'
bold_font        family=MonoLisaCode variable_name=MonoLisaCodeRegular style=MonoLisaCodeRegular-SemiBold features='dlig cv07 ss12 ss13'
italic_font      family=MonoLisaCode variable_name=MonoLisaCodeItalic style=MonoLisaCode-Italic features='dlig cv07 ss12 ss13 ss01'
bold_italic_font family=MonoLisaCode variable_name=MonoLisaCodeItalic style=MonoLisaCodeItalic-SemiBold features='dlig cv07 ss12 ss13 ss01'
# END_KITTY_FONTS

font_size        18.0

# Give breathing room between the text baseline and underline.
modify_font      underline_position 3

#: }}}

#: Cursor customization {{{

# Disable blinking — it is too distracting.
cursor_blink_interval 0

#: }}}

#: Color scheme {{{

# BEGIN_KITTY_THEME
# Kanagawa
include current-theme.conf
# END_KITTY_THEME

#: }}}

#: Advanced {{{

# Disable changing the cursor and let shell configuration handle that.
shell_integration no-cursor

#: }}}

#: OS specific tweaks {{{

# Allow passing through 'alt' to terminal applications.
macos_option_as_alt left

#: }}}

#: Keyboard shortcuts {{{

# Open windows with the same working directory as that of the active window.
map cmd+enter new_window_with_cwd
map kitty_mod+enter new_window_with_cwd

#: }}}
